### ISSUE TITLE
Gsm module

### ISSUE THREAD

**Issue by Mssdgh** [chandravaran/Smart_PrePaid_Electric_Meter#1]
Please upload gsm module

**Comment by chandravaran** [comment]
The gsm module has been added with the latest commit
Please follow the instructions as shown in this video to add the gsm module into your environment, the required files are updated.
https://youtu.be/Gvyk9Ttw_EM

**Comment by Mssdgh** [comment]
Sir, please upload code which are used in gsm module to run it properly.

**Comment by chandravaran** [comment]
https://youtu.be/N5ecV7iOsyY

Please look at this video to understand what you are doing wrong. The .hex file for the gsm module has already been uploaded in the gsm folder

**Comment by Srikar2670** [comment]
how the zero crossing detector detects phase angle and how it is implemented in code and how we connect this only using one Arduino
